<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Mail;
use App\Mail\UserWelcomeMail;

class UserController extends Controller
{
    // Fetch all users
    public function fetchAll()
    {
        return response()->json(User::all());
    }

    // Create new user with autogenerated password
    public function store(Request $request)
    {
        $validated = $request->validate([
            'name'  => 'required|string|max:255',
            'email' => 'required|email|unique:users,email',
        ]);

        $password = Str::random(8);

        $user = User::create([
            'name'     => $validated['name'],
            'email'    => $validated['email'],
            'password' => Hash::make($password),
            'role'     => 'user',
        ]);

        // Send credentials via email
        Mail::to($user->email)->send(new UserWelcomeMail($user, $password));

        return response()->json(['message' => 'User created and credentials sent.'], 201);
    }
    // Update user info
    public function update(Request $request, User $user)
    {
        $validated = $request->validate([
            'name'  => 'required|string|max:255',
            'email' => 'required|email|unique:users,email,' . $user->id,
            'role'  => 'required|in:user,admin',
        ]);

        $user->update($validated);

        return response()->json(['message' => 'User updated successfully']);
    }


    // Delete a user
    public function destroy($id)
    {
        $user = User::findOrFail($id);
        $user->delete();

        return response()->json(['message' => 'User deleted successfully']);
    }
}
